config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "photo_galleries#index"
  resources :photo_galleries do
    resources :photos
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/photo.rb
# frozen_string_literal: true

class Photo < ApplicationRecord
  belongs_to :photo_gallery, inverse_of: :photos
  has_one_attached :image, dependent: :destroy

  validates :name, presence: true, uniqueness: true
  validates(
    :image,
    attached: true,
    content_type: %r{\Aimage/.*\z},
    size:
      { less_than: 100.megabytes, message: 'is too large' }
  )
end

app/models/photo_gallery.rb
# frozen_string_literal: true

class PhotoGallery < ApplicationRecord
  belongs_to :user, inverse_of: :photo_galleries
  has_many :photos, inverse_of: :photo_gallery, dependent: :destroy

  validates :name, :description, presence: true
  validates :name, uniqueness: true
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  validates :first_name, :last_name, presence: true

  has_many :photo_galleries, inverse_of: :user, dependent: :destroy
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :current_user
  # attr_accessor :current_user

  def current_user
    @current_user ||= User.first || User.create!(first_name: 'default', last_name: 'default')
  end

  helper_method :current_user
end

app/controllers/photo_galleries_controller.rb
# frozen_string_literal: true

class PhotoGalleriesController < ApplicationController
  before_action :photo_gallery, only: %i[show edit update destroy]

  def index
    @photo_galleries = current_user.photo_galleries
  end

  def show; end

  def new
    @photo_gallery = PhotoGallery.new
  end

  def create
    @photo_gallery = current_user.photo_galleries.build(photo_gallery_params)
    if @photo_gallery.save
      respond_to do |format|
        format.html { redirect_to photo_galleries_path, notice: 'Gallery was successfully created.' }
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    render :edit
  end

  def update
    if @photo_gallery.update(photo_gallery_params)
      respond_to do |format|
        format.html { redirect_to photo_galleries_path, notice: 'Gallery was successfully updated.' }
      end
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @photo_gallery.destroy
    respond_to do |format|
      format.html { redirect_to photo_galleries_path, notice: 'Gallery was successfully deleted.' }
    end
  end

  private

  def photo_gallery
    @photo_gallery = current_user.photo_galleries.find(params[:id])
  end

  def photo_gallery_params
    params.require(:photo_gallery).permit(:name, :description)
  end
end

app/controllers/photos_controller.rb
# frozen_string_literal: true

class PhotosController < ApplicationController
  before_action :photo, only: %i[show edit update destroy]

  def index
    @photos = photo_gallery.photos
  end

  def new
    @photo_gallery = photo_gallery
  end

  def create
    @photo = photo_gallery.photos.build(photo_params)
    if @photo.save
      respond_to do |format|
        format.html { redirect_to photo_gallery_photos_path(photo_gallery), notice: 'Photo was successfully created.' }
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    render :edit
  end

  def update
    if @photo.update(photo_params)
      respond_to do |format|
        format.html { redirect_to photo_gallery_photos_path(photo_gallery), notice: 'Photo was successfully updated.' }
      end
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @photo.destroy
    respond_to do |format|
      format.html { redirect_to photo_gallery_photos_path(photo_gallery), notice: 'Photo was successfully deleted.' }
    end
  end

  private

  def photo_gallery
    @photo_gallery ||= current_user.photo_galleries.find(params[:photo_gallery_id])
  end

  def photo
    @photo ||= photo_gallery.photos.find(params[:id])
  end

  def photo_params
    params.require(:photo).permit(:name, :description, :shooting_date, :image)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gallery</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">

  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<%= yield %>
</body>
</html>

app/views/photo_galleries/_form.html.erb
<%= simple_form_for photo_gallery, html: { class: "photo-gallery form" } do |f| %>
  <% if photo_gallery.errors.any? %>
    <div class="error-message">
      <%= photo_gallery.errors.full_messages.to_sentence.capitalize %>
    </div>
  <% end %>
  <%= f.input :name, input_html: { autofocus: true } %>
  <%= f.input :description, input_html: { autofocus: true } %>
  <%= link_to "Cancel", photo_galleries_path, class: "btn btn--light" %>
  <%= f.submit class: "btn btn--secondary" %>
<% end %>

app/views/photo_galleries/_photo_gallery.html.erb
<div class="photo-gallery">
  <%= link_to photo_gallery.name, photo_gallery_path(photo_gallery) %>
  <%= link_to photo_gallery.description, photo_gallery_path(photo_gallery) %>
  <div class="photo-gallery__actions">
    <%= button_to(
          "Delete",
          photo_gallery_path(photo_gallery),
          method: :delete, class: "btn btn--light",
          data: photo_gallery.photos.exists? ? { confirm: "Are you sure?" } : nil
        )
    %>
    <%= link_to "Edit", edit_photo_gallery_path(photo_gallery), class: "btn btn--light" %>
  </div>
</div>

app/views/photo_galleries/edit.html.erb
<h1>Edit the gallery</h1>

<%= simple_form_for(
      @photo_gallery,
      url: photo_gallery_path(@photo_gallery),
      method: :patch,
      html: { class: "photo-gallery form" },
      local: true
    ) do |f| %>

  <%= f.input :name, input_html: { autofocus: true } %>
  <%= f.input :description %>
  <%= link_to "Cancel", photo_galleries_path, class: "btn btn--light" %>
  <%= f.submit class: "btn btn--secondary" %>

<% end %>

app/views/photo_galleries/index.html.erb
<div class="container">
  <div class="header">
    <h1>My Photo Galleries</h1>
    <%= link_to "New Gallery", new_photo_gallery_path, class: "btn btn--primary" %>
  </div>
  <div>
    <%= render @photo_galleries %>
  </div>
</div>

app/views/photo_galleries/new.html.erb
<main class="container">
  <%= link_to sanitize("&larr; Back to galleries"), photo_galleries_path %>

  <div class="header">
    <h1>New Gallery</h1>
  </div>
  <%= render "form", photo_gallery: @photo_gallery %>
</main>

app/views/photo_galleries/show.html.erb
<main class="container">
  <%= link_to sanitize("&larr; Back to Galleries"), photo_galleries_path %>
  <div>
    <h1>
      <%= @photo_gallery.name %>
    </h1>
    <p>
      <%= @photo_gallery.description %>
    </p>

    <div class="header">
      <h5>
        My photos
      </h5>
    </div>

    <%= render @photo_gallery.photos %>
    <div class="header">
      <h2>Add new photo:</h2>
    </div>
    <%= render 'photos/form' %>
  </div>
</main>

app/views/photos/_form.html.erb
<%= simple_form_for [@photo_gallery, @photo_gallery.photos.build],  html: { class: "photo-gallery form" }  do |f| %>
  <%= f.input :name, input_html: { autofocus: true } %>
  <%= f.input :description %>
  <%= f.input :shooting_date %>
  <%= f.input :image %>
  <%= link_to "Cancel", photo_gallery_photos_path(@photo_gallery), class: "btn btn--light" %>
  <%= f.submit class: "btn btn--secondary" %>
<% end %>

app/views/photos/_photo.html.erb
<div class="photo">
  <%= image_tag url_for(photo.image) if photo.image.attached? %>
  <p>
    <strong>Name:</strong>
    <%= photo.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= photo.description %>
  </p>

  <p>
    <strong>Shooting Date:</strong>
    <%= photo.shooting_date %>
  </p>
  <div class="photo-gallery__actions">
    <%= button_to "Delete", photo_gallery_photo_path(photo.photo_gallery, photo), method: :delete, class: "btn btn--light" %>
    <%= link_to "Edit", edit_photo_gallery_photo_path(photo.photo_gallery, photo), class: "btn btn--light" %>
  </div>
</div>

app/views/photos/edit.html.erb
<div class="header">
  <h1>Edit the photo</h1>
</div>

<%= simple_form_for(
      [@photo_gallery, @photo],
      url: photo_gallery_photo_path(@photo_gallery, @photo),
      method: :patch,
      html: { class: "photo-gallery form" },
      local: true
    ) do |f| %>
  <%= f.input :name, input_html: { autofocus: true } %>
  <%= f.input :description %>
  <%= f.input :shooting_date %>
  <%= f.input :image %>
  <%= link_to "Cancel", photo_gallery_photos_path(@photo_gallery), class: "btn btn--light" %>
  <%= f.submit class: "btn btn--secondary" %>
<% end %>

app/views/photos/index.html.erb
<div class="container">
  <div class="header">
    <h1>My Photos</h1>
    <%= link_to "Add new photo", new_photo_gallery_photo_path, class: "btn btn--primary" %>
  </div>
  <div>
    <%= render @photos %>
  </div>
</div>

app/views/photos/new.html.erb
<main class="container">
  <%= link_to sanitize("&larr; Back to galleries"), photo_gallery_photos_path %>

  <div class="header">
    <h1>New Image</h1>
  </div>
  <%= render "form", photo: @photo %>
</main>